### ISSUE TITLE
AndieGraph will not locate ROM

### ISSUE THREAD

**Issue by geekalert** [dgmltn/AndieGraph#3]
So, on my Samsung Avant, it was no problem. I placed the ROM files in the root directory of the internal SDCARD and they were located immediately. However, I got my new Samsung Note4, and I can't get AndieGraph to locate the ROMs at all. I would if it is because my system has labeled the internal sdcard as 'sdcard0' and external card as 'extsdcard' (not 'sdcard' and 'sdcard-ext')?

**Comment by geekalert** [comment]
(sorry, that should be 'I wonder if')

**Comment by dgmltn** [comment]
AndieGraph [searches for ROMs](https://github.com/dgmltn/AndieGraph/blob/7d052fab931e78fadb3373b5eac19e80a3825a66/app/src/main/java/net/supware/tipro/FindRomsTask.java#L19) in the following locations:

`private String[] SEARCH_LOCATIONS = { Environment.getExternalStorageDirectory().getAbsolutePath(), “/mnt/sdcard”, “/mnt/sdcard-ext” };
`

So that could be. I added the special case ("/mnt/sdcard" and "/mnt/sdcard-ext") for Samsung phones a while back when Samsung didn't return the right thing from getExternalStorageDirectory(). I guess they still haven't fixed that bug. What path is getExternalStorageDirectory() returning on your Note4?
